name: Semgrep

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '36 3 * * 1'
  workflow_dispatch:


permissions:
  contents: read

jobs:
  semgrep-full:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: clone application source code
        uses: actions/checkout@v3
      - name: full scan
        run: |
          semgrep --sarif --output semgrep.sarif --metrics=off --config="p/default"

      - name: package-logs
        if: always()
        # run: tar czf semgrep-logs.tgz ~/.semgrep/last.log
        run: find . -name *log && find . -name *sarif

      # - name: upload-logs
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: semgrep-logs.tgz
      #     path: semgrep-logs.tgz
      #     retention-days: 10

      - name: upload-sarif
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: semgrep.sarif
          path: semgrep.sarif
          retention-days: 10

      # Upload SARIF file generated in previous step
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
          category: semgrep
        # if: always()
